/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

import Backend.Games;
import java.awt.Color;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;

/**
 *
 * @author megan
 */
public class CrosswordScreen extends javax.swing.JFrame
{
    //creating a games object in order to use the methods in that class
    Games game = new Games();
    
    /**
     * Creates new form CrosswordScreen
     */
    public CrosswordScreen() throws IOException
    {
        initComponents();
        //setting full screen
        this.setExtendedState(this.MAXIMIZED_BOTH); 
        
        //selecting a crossword
        game.setCrossword();
        BufferedImage crosswordImg = ImageIO.read(new File(game.getCrosswordPicturePathway()));
        crosswordPic.setIcon(new ImageIcon(crosswordImg));
        BufferedImage cluesImg = ImageIO.read(new File(game.getCrosswordAnswerPathway()));
        crosswordCluesPic.setIcon(new ImageIcon(cluesImg));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        infoButton = new javax.swing.JButton();
        diaryButton = new javax.swing.JButton();
        homeButton = new javax.swing.JButton();
        backButton = new javax.swing.JButton();
        crosswordCluesPic = new javax.swing.JLabel();
        crosswordPic = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        answerBox5 = new javax.swing.JTextField();
        answerBox3 = new javax.swing.JTextField();
        answerBox4 = new javax.swing.JTextField();
        answerBox2 = new javax.swing.JTextField();
        answerBox1 = new javax.swing.JTextField();
        checkButton1 = new javax.swing.JButton();
        checkButton2 = new javax.swing.JButton();
        checkButton3 = new javax.swing.JButton();
        checkButton4 = new javax.swing.JButton();
        checkButton5 = new javax.swing.JButton();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        infoButton.setBackground(new java.awt.Color(15, 28, 33));
        infoButton.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        infoButton.setForeground(new java.awt.Color(139, 118, 82));
        infoButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/infoIcon.png"))); // NOI18N
        infoButton.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(139, 118, 82), 5, true));
        infoButton.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                infoButtonActionPerformed(evt);
            }
        });
        getContentPane().add(infoButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(1250, 110, -1, 60));

        diaryButton.setBackground(new java.awt.Color(15, 28, 33));
        diaryButton.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        diaryButton.setForeground(new java.awt.Color(139, 118, 82));
        diaryButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/diaryIcon.jpg"))); // NOI18N
        diaryButton.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(139, 118, 82), 5, true));
        diaryButton.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                diaryButtonActionPerformed(evt);
            }
        });
        getContentPane().add(diaryButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(1150, 30, -1, 70));

        homeButton.setBackground(new java.awt.Color(15, 28, 33));
        homeButton.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        homeButton.setForeground(new java.awt.Color(139, 118, 82));
        homeButton.setText("HOME");
        homeButton.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(139, 118, 82), 5, true));
        homeButton.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                homeButtonActionPerformed(evt);
            }
        });
        getContentPane().add(homeButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(1240, 30, 90, 70));

        backButton.setBackground(new java.awt.Color(15, 28, 33));
        backButton.setFont(new java.awt.Font("High Tower Text", 1, 24)); // NOI18N
        backButton.setForeground(new java.awt.Color(139, 118, 82));
        backButton.setText("<<");
        backButton.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(139, 118, 82), 5, true));
        backButton.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                backButtonActionPerformed(evt);
            }
        });
        getContentPane().add(backButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, 80, 50));
        getContentPane().add(crosswordCluesPic, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 460, 680, -1));
        getContentPane().add(crosswordPic, new org.netbeans.lib.awtextra.AbsoluteConstraints(146, 80, 470, 330));

        jLabel3.setFont(new java.awt.Font("Perpetua Titling MT", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(139, 118, 82));
        jLabel3.setText("1.");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 150, 50, -1));

        jLabel4.setFont(new java.awt.Font("Perpetua Titling MT", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(139, 118, 82));
        jLabel4.setText("3.");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 300, 50, -1));

        jLabel5.setFont(new java.awt.Font("Perpetua Titling MT", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(139, 118, 82));
        jLabel5.setText("4.");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 390, 50, -1));

        jLabel6.setFont(new java.awt.Font("Perpetua Titling MT", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(139, 118, 82));
        jLabel6.setText("5.");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 470, 50, -1));

        jLabel7.setFont(new java.awt.Font("Perpetua Titling MT", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(139, 118, 82));
        jLabel7.setText("2.");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 220, 50, -1));

        answerBox5.setBackground(new java.awt.Color(15, 28, 33));
        answerBox5.setFont(new java.awt.Font("Perpetua Titling MT", 1, 18)); // NOI18N
        answerBox5.setForeground(new java.awt.Color(139, 118, 82));
        answerBox5.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(139, 118, 82), 5, true));
        answerBox5.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                answerBox5ActionPerformed(evt);
            }
        });
        getContentPane().add(answerBox5, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 460, 360, 50));

        answerBox3.setBackground(new java.awt.Color(15, 28, 33));
        answerBox3.setFont(new java.awt.Font("Perpetua Titling MT", 1, 18)); // NOI18N
        answerBox3.setForeground(new java.awt.Color(139, 118, 82));
        answerBox3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(139, 118, 82), 5, true));
        answerBox3.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                answerBox3ActionPerformed(evt);
            }
        });
        getContentPane().add(answerBox3, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 290, 360, 50));

        answerBox4.setBackground(new java.awt.Color(15, 28, 33));
        answerBox4.setFont(new java.awt.Font("Perpetua Titling MT", 1, 18)); // NOI18N
        answerBox4.setForeground(new java.awt.Color(139, 118, 82));
        answerBox4.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(139, 118, 82), 5, true));
        answerBox4.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                answerBox4ActionPerformed(evt);
            }
        });
        getContentPane().add(answerBox4, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 380, 360, 50));

        answerBox2.setBackground(new java.awt.Color(15, 28, 33));
        answerBox2.setFont(new java.awt.Font("Perpetua Titling MT", 1, 18)); // NOI18N
        answerBox2.setForeground(new java.awt.Color(139, 118, 82));
        answerBox2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(139, 118, 82), 5, true));
        answerBox2.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                answerBox2ActionPerformed(evt);
            }
        });
        getContentPane().add(answerBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 210, 360, 50));

        answerBox1.setBackground(new java.awt.Color(15, 28, 33));
        answerBox1.setFont(new java.awt.Font("Perpetua Titling MT", 1, 18)); // NOI18N
        answerBox1.setForeground(new java.awt.Color(139, 118, 82));
        answerBox1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(139, 118, 82), 5, true));
        answerBox1.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                answerBox1ActionPerformed(evt);
            }
        });
        getContentPane().add(answerBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 130, 360, 50));

        checkButton1.setBackground(new java.awt.Color(15, 28, 33));
        checkButton1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        checkButton1.setForeground(new java.awt.Color(139, 118, 82));
        checkButton1.setText("CHECK");
        checkButton1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(139, 118, 82), 5, true));
        checkButton1.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                checkButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(checkButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1140, 140, 80, 40));

        checkButton2.setBackground(new java.awt.Color(15, 28, 33));
        checkButton2.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        checkButton2.setForeground(new java.awt.Color(139, 118, 82));
        checkButton2.setText("CHECK");
        checkButton2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(139, 118, 82), 5, true));
        checkButton2.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                checkButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(checkButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1140, 220, 80, 40));

        checkButton3.setBackground(new java.awt.Color(15, 28, 33));
        checkButton3.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        checkButton3.setForeground(new java.awt.Color(139, 118, 82));
        checkButton3.setText("CHECK");
        checkButton3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(139, 118, 82), 5, true));
        checkButton3.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                checkButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(checkButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1140, 300, 80, 40));

        checkButton4.setBackground(new java.awt.Color(15, 28, 33));
        checkButton4.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        checkButton4.setForeground(new java.awt.Color(139, 118, 82));
        checkButton4.setText("CHECK");
        checkButton4.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(139, 118, 82), 5, true));
        checkButton4.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                checkButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(checkButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1140, 390, 80, 40));

        checkButton5.setBackground(new java.awt.Color(15, 28, 33));
        checkButton5.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        checkButton5.setForeground(new java.awt.Color(139, 118, 82));
        checkButton5.setText("CHECK");
        checkButton5.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(139, 118, 82), 5, true));
        checkButton5.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                checkButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(checkButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(1140, 470, 80, 40));

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/redBackground.png"))); // NOI18N
        getContentPane().add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -330, 1400, 1200));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void infoButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_infoButtonActionPerformed
    {//GEN-HEADEREND:event_infoButtonActionPerformed
        try
        {
            new ObjectiveScreen().setVisible(true);
        } catch (SQLException ex)
        {
            Logger.getLogger(CrosswordScreen.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_infoButtonActionPerformed

    private void diaryButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_diaryButtonActionPerformed
    {//GEN-HEADEREND:event_diaryButtonActionPerformed
        try
        {
            new DiaryScreen().setVisible(true);
        } catch (SQLException ex)
        {
            Logger.getLogger(CrosswordScreen.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_diaryButtonActionPerformed

    private void homeButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_homeButtonActionPerformed
    {//GEN-HEADEREND:event_homeButtonActionPerformed
        this.dispose();
        new UserScreen().setVisible(true);
    }//GEN-LAST:event_homeButtonActionPerformed

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_backButtonActionPerformed
    {//GEN-HEADEREND:event_backButtonActionPerformed
        this.dispose();
        new DiningRoom().setVisible(true);
    }//GEN-LAST:event_backButtonActionPerformed

    private void answerBox5ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_answerBox5ActionPerformed
    {//GEN-HEADEREND:event_answerBox5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_answerBox5ActionPerformed

    private void answerBox3ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_answerBox3ActionPerformed
    {//GEN-HEADEREND:event_answerBox3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_answerBox3ActionPerformed

    private void answerBox4ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_answerBox4ActionPerformed
    {//GEN-HEADEREND:event_answerBox4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_answerBox4ActionPerformed

    private void answerBox2ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_answerBox2ActionPerformed
    {//GEN-HEADEREND:event_answerBox2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_answerBox2ActionPerformed

    private void answerBox1ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_answerBox1ActionPerformed
    {//GEN-HEADEREND:event_answerBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_answerBox1ActionPerformed

    private void checkButton1ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_checkButton1ActionPerformed
    {//GEN-HEADEREND:event_checkButton1ActionPerformed
        try
        {
            game.checkAnswer(1, answerBox1.getText());
            if(game.checkAnswer(1, answerBox1.getText()))
            {
                answerBox1.setBackground(Color.green);
                //locking the answer box
                answerBox1.setEditable(false);
            }
            else
            {
                answerBox1.setBackground(Color.red);
            }
        } catch (SQLException ex)
        {
            Logger.getLogger(CrosswordScreen.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex)
        {
            Logger.getLogger(CrosswordScreen.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_checkButton1ActionPerformed

    private void checkButton2ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_checkButton2ActionPerformed
    {//GEN-HEADEREND:event_checkButton2ActionPerformed
        try
        {
            game.checkAnswer(2, answerBox2.getText());
            if(game.checkAnswer(2, answerBox2.getText()))
            {
                answerBox2.setBackground(Color.green);
                //locking the answer box
                answerBox2.setEditable(false);
            }
            else
            {
                answerBox2.setBackground(Color.red);
            }
        } catch (SQLException ex)
        {
            Logger.getLogger(CrosswordScreen.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex)
        {
            Logger.getLogger(CrosswordScreen.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_checkButton2ActionPerformed

    private void checkButton3ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_checkButton3ActionPerformed
    {//GEN-HEADEREND:event_checkButton3ActionPerformed
        try
        {
            game.checkAnswer(3, answerBox3.getText());
            if(game.checkAnswer(3, answerBox3.getText()))
            {
                answerBox3.setBackground(Color.green);
                //locking the answer box
                answerBox3.setEditable(false);
            }
            else
            {
                answerBox3.setBackground(Color.red);
            }
        } catch (SQLException ex)
        {
            Logger.getLogger(CrosswordScreen.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex)
        {
            Logger.getLogger(CrosswordScreen.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_checkButton3ActionPerformed

    private void checkButton4ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_checkButton4ActionPerformed
    {//GEN-HEADEREND:event_checkButton4ActionPerformed
        try
        {
            game.checkAnswer(4, answerBox4.getText());
            if(game.checkAnswer(4, answerBox4.getText()))
            {
                answerBox4.setBackground(Color.green);
                //locking the answer box
                answerBox4.setEditable(false);
            }
            else
            {
                answerBox4.setBackground(Color.red);
            }
        } catch (SQLException ex)
        {
            Logger.getLogger(CrosswordScreen.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex)
        {
            Logger.getLogger(CrosswordScreen.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_checkButton4ActionPerformed

    private void checkButton5ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_checkButton5ActionPerformed
    {//GEN-HEADEREND:event_checkButton5ActionPerformed
        try
        {
            game.checkAnswer(5, answerBox5.getText());
            if(game.checkAnswer(5, answerBox5.getText()))
            {
                answerBox5.setBackground(Color.green);
                //locking the answer box
                answerBox5.setEditable(false);
            }
            else
            {
                answerBox5.setBackground(Color.red);
            }
        } catch (SQLException ex)
        {
            Logger.getLogger(CrosswordScreen.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex)
        {
            Logger.getLogger(CrosswordScreen.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_checkButton5ActionPerformed

  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField answerBox1;
    private javax.swing.JTextField answerBox2;
    private javax.swing.JTextField answerBox3;
    private javax.swing.JTextField answerBox4;
    private javax.swing.JTextField answerBox5;
    private javax.swing.JButton backButton;
    private javax.swing.JLabel background;
    private javax.swing.JButton checkButton1;
    private javax.swing.JButton checkButton2;
    private javax.swing.JButton checkButton3;
    private javax.swing.JButton checkButton4;
    private javax.swing.JButton checkButton5;
    private javax.swing.JLabel crosswordCluesPic;
    private javax.swing.JLabel crosswordPic;
    private javax.swing.JButton diaryButton;
    private javax.swing.JButton homeButton;
    private javax.swing.JButton infoButton;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    // End of variables declaration//GEN-END:variables
}
