/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

import Backend.Diary;
import Backend.UserManager;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;

/**
 *
 * @author megan
 */
public class DiaryScreen extends javax.swing.JFrame
{

    /**
     * Creates new form DiaryScreen
     */
    public DiaryScreen() throws SQLException
    {
        initComponents();
        
        //populating the lists
        UserManager userManager = new UserManager();
        Diary diary = new Diary();
        
        ArrayList<String> characterNames = diary.getCharacterList();
        DefaultListModel listModel2 = new DefaultListModel();
        listModel2.addAll(characterNames);
        characterList.setModel(listModel2);
        
        ArrayList<String> clueNames = diary.getListClues();
        DefaultListModel listModel1 = new DefaultListModel();
        listModel1.addAll(clueNames);
        listModel1.addAll(characterNames);
        clueList.setModel(listModel1);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jLabel1 = new javax.swing.JLabel();
        homeButton = new javax.swing.JButton();
        backButton = new javax.swing.JButton();
        map = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        characterList = new javax.swing.JList<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        clueList = new javax.swing.JList<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        infoTextArea = new javax.swing.JTextArea();
        diary = new javax.swing.JLabel();
        background = new javax.swing.JLabel();

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        homeButton.setBackground(new java.awt.Color(15, 28, 33));
        homeButton.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        homeButton.setForeground(new java.awt.Color(139, 118, 82));
        homeButton.setText("HOME");
        homeButton.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(139, 118, 82), 5, true));
        homeButton.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                homeButtonActionPerformed(evt);
            }
        });
        getContentPane().add(homeButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(1220, 30, 110, 50));

        backButton.setBackground(new java.awt.Color(15, 28, 33));
        backButton.setFont(new java.awt.Font("High Tower Text", 1, 24)); // NOI18N
        backButton.setForeground(new java.awt.Color(139, 118, 82));
        backButton.setText("<<");
        backButton.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(139, 118, 82), 5, true));
        backButton.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                backButtonActionPerformed(evt);
            }
        });
        getContentPane().add(backButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 90, 50));

        map.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(139, 118, 82), 5, true));
        getContentPane().add(map, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 140, 480, 220));

        characterList.setBackground(new java.awt.Color(221, 222, 222));
        characterList.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(139, 118, 82), 5, true));
        characterList.setFont(new java.awt.Font("Felix Titling", 0, 18)); // NOI18N
        characterList.setForeground(new java.awt.Color(15, 28, 33));
        characterList.setModel(new javax.swing.AbstractListModel<String>()
        {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        characterList.addListSelectionListener(new javax.swing.event.ListSelectionListener()
        {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt)
            {
                characterListValueChanged(evt);
            }
        });
        jScrollPane3.setViewportView(characterList);

        getContentPane().add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 380, 210, 210));

        clueList.setBackground(new java.awt.Color(221, 222, 222));
        clueList.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(139, 118, 82), 5, true));
        clueList.setFont(new java.awt.Font("Felix Titling", 0, 18)); // NOI18N
        clueList.setForeground(new java.awt.Color(15, 28, 33));
        clueList.setModel(new javax.swing.AbstractListModel<String>()
        {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        clueList.addListSelectionListener(new javax.swing.event.ListSelectionListener()
        {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt)
            {
                clueListValueChanged(evt);
            }
        });
        jScrollPane2.setViewportView(clueList);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 380, 210, 210));

        infoTextArea.setEditable(false);
        infoTextArea.setBackground(new java.awt.Color(222, 222, 222));
        infoTextArea.setColumns(20);
        infoTextArea.setFont(new java.awt.Font("Felix Titling", 0, 18)); // NOI18N
        infoTextArea.setForeground(new java.awt.Color(15, 28, 33));
        infoTextArea.setLineWrap(true);
        infoTextArea.setRows(5);
        infoTextArea.setWrapStyleWord(true);
        infoTextArea.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(139, 118, 82), 5, true));
        jScrollPane1.setViewportView(infoTextArea);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 140, 420, 490));

        diary.setIcon(new javax.swing.ImageIcon("C:\\Users\\megan\\OneDrive\\Documents\\NetBeansProjects\\PAT2023\\resources\\diary.png")); // NOI18N
        getContentPane().add(diary, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 100, 1170, 550));

        background.setIcon(new javax.swing.ImageIcon("C:\\Users\\megan\\OneDrive\\Documents\\NetBeansProjects\\PAT2023\\resources\\background.jpg")); // NOI18N
        getContentPane().add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(-35, -104, 1400, 840));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_backButtonActionPerformed
    {//GEN-HEADEREND:event_backButtonActionPerformed
        this.dispose();
    }//GEN-LAST:event_backButtonActionPerformed

    private void homeButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_homeButtonActionPerformed
    {//GEN-HEADEREND:event_homeButtonActionPerformed
        this.dispose();
        new UserScreen().setVisible(true);
    }//GEN-LAST:event_homeButtonActionPerformed

    private void clueListValueChanged(javax.swing.event.ListSelectionEvent evt)//GEN-FIRST:event_clueListValueChanged
    {//GEN-HEADEREND:event_clueListValueChanged
        try
        {
            //creating a diary object
            Diary diary = new Diary();
            
            //getting the information
            infoTextArea.setText(diary.getClueData(clueList.getSelectedValue()));
        } catch (SQLException ex)
        {
            Logger.getLogger(DiaryScreen.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_clueListValueChanged

    private void characterListValueChanged(javax.swing.event.ListSelectionEvent evt)//GEN-FIRST:event_characterListValueChanged
    {//GEN-HEADEREND:event_characterListValueChanged
       try
        {
            //creating a diary object
            Diary diary = new Diary();
            
            //getting the information
            infoTextArea.setText(diary.getCharacterData(characterList.getSelectedValue()));
        } catch (SQLException ex)
        {
            Logger.getLogger(DiaryScreen.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_characterListValueChanged



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backButton;
    private javax.swing.JLabel background;
    private javax.swing.JList<String> characterList;
    private javax.swing.JList<String> clueList;
    private javax.swing.JLabel diary;
    private javax.swing.JButton homeButton;
    private javax.swing.JTextArea infoTextArea;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel map;
    // End of variables declaration//GEN-END:variables
}
