/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

/**
 *
 * @author megan
 */
public class FindingGameScreen extends javax.swing.JFrame
{

    /**
     * Creates new form FindingGameScreen
     */
    public FindingGameScreen()
    {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        spriteButton1 = new javax.swing.JButton();
        spriteButton2 = new javax.swing.JButton();
        spriteButton3 = new javax.swing.JButton();
        spriteButton4 = new javax.swing.JButton();
        spriteButton5 = new javax.swing.JButton();
        spriteButton6 = new javax.swing.JButton();
        infoButton = new javax.swing.JButton();
        backButton = new javax.swing.JButton();
        homeButton = new javax.swing.JButton();
        diaryButton = new javax.swing.JButton();
        spritesFoundLabel = new javax.swing.JLabel();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        spriteButton1.setIcon(new javax.swing.ImageIcon("C:\\Users\\megan\\OneDrive\\Documents\\NetBeansProjects\\PAT2023\\resources\\picture.jpg")); // NOI18N
        spriteButton1.setBorder(null);
        getContentPane().add(spriteButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1120, 310, -1, 30));

        spriteButton2.setIcon(new javax.swing.ImageIcon("C:\\Users\\megan\\OneDrive\\Documents\\NetBeansProjects\\PAT2023\\resources\\picture.jpg")); // NOI18N
        spriteButton2.setBorder(null);
        spriteButton2.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                spriteButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(spriteButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 650, 30, 30));

        spriteButton3.setIcon(new javax.swing.ImageIcon("C:\\Users\\megan\\OneDrive\\Documents\\NetBeansProjects\\PAT2023\\resources\\picture.jpg")); // NOI18N
        spriteButton3.setBorder(null);
        getContentPane().add(spriteButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 330, 30, 30));

        spriteButton4.setIcon(new javax.swing.ImageIcon("C:\\Users\\megan\\OneDrive\\Documents\\NetBeansProjects\\PAT2023\\resources\\picture.jpg")); // NOI18N
        spriteButton4.setBorder(null);
        spriteButton4.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                spriteButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(spriteButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 140, 20, 30));

        spriteButton5.setIcon(new javax.swing.ImageIcon("C:\\Users\\megan\\OneDrive\\Documents\\NetBeansProjects\\PAT2023\\resources\\picture.jpg")); // NOI18N
        spriteButton5.setBorder(null);
        getContentPane().add(spriteButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(1110, 140, 10, 20));

        spriteButton6.setIcon(new javax.swing.ImageIcon("C:\\Users\\megan\\OneDrive\\Documents\\NetBeansProjects\\PAT2023\\resources\\picture.jpg")); // NOI18N
        spriteButton6.setBorder(null);
        getContentPane().add(spriteButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 110, 10, 20));

        infoButton.setBackground(new java.awt.Color(15, 28, 33));
        infoButton.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        infoButton.setForeground(new java.awt.Color(139, 118, 82));
        infoButton.setIcon(new javax.swing.ImageIcon("C:\\Users\\megan\\OneDrive\\Documents\\NetBeansProjects\\PAT2023\\resources\\infoIcon.png")); // NOI18N
        infoButton.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(139, 118, 82), 5, true));
        infoButton.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                infoButtonActionPerformed(evt);
            }
        });
        getContentPane().add(infoButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(1260, 110, 70, 60));

        backButton.setBackground(new java.awt.Color(15, 28, 33));
        backButton.setFont(new java.awt.Font("High Tower Text", 1, 24)); // NOI18N
        backButton.setForeground(new java.awt.Color(139, 118, 82));
        backButton.setText("<<");
        backButton.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(139, 118, 82), 5, true));
        backButton.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                backButtonActionPerformed(evt);
            }
        });
        getContentPane().add(backButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 90, 50));

        homeButton.setBackground(new java.awt.Color(15, 28, 33));
        homeButton.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        homeButton.setForeground(new java.awt.Color(139, 118, 82));
        homeButton.setText("HOME");
        homeButton.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(139, 118, 82), 5, true));
        homeButton.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                homeButtonActionPerformed(evt);
            }
        });
        getContentPane().add(homeButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(1220, 30, 110, 70));

        diaryButton.setBackground(new java.awt.Color(15, 28, 33));
        diaryButton.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        diaryButton.setForeground(new java.awt.Color(139, 118, 82));
        diaryButton.setIcon(new javax.swing.ImageIcon("C:\\Users\\megan\\OneDrive\\Documents\\NetBeansProjects\\PAT2023\\resources\\diaryIcon.jpg")); // NOI18N
        diaryButton.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(139, 118, 82), 5, true));
        diaryButton.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                diaryButtonActionPerformed(evt);
            }
        });
        getContentPane().add(diaryButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(1130, 30, 70, 70));

        spritesFoundLabel.setBackground(new java.awt.Color(15, 28, 33));
        spritesFoundLabel.setFont(new java.awt.Font("Perpetua Titling MT", 1, 18)); // NOI18N
        spritesFoundLabel.setForeground(new java.awt.Color(139, 118, 82));
        spritesFoundLabel.setText("jLabel1");
        spritesFoundLabel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(139, 118, 82), 5, true));
        spritesFoundLabel.setOpaque(true);
        getContentPane().add(spritesFoundLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(1024, 30, 90, 70));

        background.setIcon(new javax.swing.ImageIcon("C:\\Users\\megan\\OneDrive\\Documents\\NetBeansProjects\\PAT2023\\resources\\sleepingCompartmentBackground.png")); // NOI18N
        getContentPane().add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -330, 1400, 1200));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void infoButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_infoButtonActionPerformed
    {//GEN-HEADEREND:event_infoButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_infoButtonActionPerformed

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_backButtonActionPerformed
    {//GEN-HEADEREND:event_backButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_backButtonActionPerformed

    private void homeButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_homeButtonActionPerformed
    {//GEN-HEADEREND:event_homeButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_homeButtonActionPerformed

    private void diaryButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_diaryButtonActionPerformed
    {//GEN-HEADEREND:event_diaryButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_diaryButtonActionPerformed

    private void spriteButton2ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_spriteButton2ActionPerformed
    {//GEN-HEADEREND:event_spriteButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_spriteButton2ActionPerformed

    private void spriteButton4ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_spriteButton4ActionPerformed
    {//GEN-HEADEREND:event_spriteButton4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_spriteButton4ActionPerformed



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backButton;
    private javax.swing.JLabel background;
    private javax.swing.JButton diaryButton;
    private javax.swing.JButton homeButton;
    private javax.swing.JButton infoButton;
    private javax.swing.JButton spriteButton1;
    private javax.swing.JButton spriteButton2;
    private javax.swing.JButton spriteButton3;
    private javax.swing.JButton spriteButton4;
    private javax.swing.JButton spriteButton5;
    private javax.swing.JButton spriteButton6;
    private javax.swing.JLabel spritesFoundLabel;
    // End of variables declaration//GEN-END:variables
}
