/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

import Backend.Games;
import java.io.IOException;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author megan
 */
public class FindingGameScreen extends javax.swing.JFrame
{
    //creates a game object
    Games game = new Games();
    
    /**
     * Creates new form FindingGameScreen
     */
    public FindingGameScreen()
    {
        initComponents();
        
        //setting full screen
        this.setExtendedState(this.MAXIMIZED_BOTH); 
        
        spritesFoundLabel.setText("0/6");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        spriteButton1 = new javax.swing.JButton();
        spriteButton2 = new javax.swing.JButton();
        spriteButton3 = new javax.swing.JButton();
        spriteButton4 = new javax.swing.JButton();
        spriteButton5 = new javax.swing.JButton();
        spriteButton6 = new javax.swing.JButton();
        infoButton = new javax.swing.JButton();
        backButton = new javax.swing.JButton();
        homeButton = new javax.swing.JButton();
        diaryButton = new javax.swing.JButton();
        spritesFoundLabel = new javax.swing.JLabel();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        spriteButton1.setIcon(new javax.swing.ImageIcon("C:\\Users\\megan\\OneDrive\\Documents\\NetBeansProjects\\PAT2023\\resources\\picture.jpg")); // NOI18N
        spriteButton1.setBorder(null);
        spriteButton1.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                spriteButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(spriteButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1120, 310, -1, 30));

        spriteButton2.setIcon(new javax.swing.ImageIcon("C:\\Users\\megan\\OneDrive\\Documents\\NetBeansProjects\\PAT2023\\resources\\picture.jpg")); // NOI18N
        spriteButton2.setBorder(null);
        spriteButton2.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                spriteButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(spriteButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 650, 30, 30));

        spriteButton3.setIcon(new javax.swing.ImageIcon("C:\\Users\\megan\\OneDrive\\Documents\\NetBeansProjects\\PAT2023\\resources\\picture.jpg")); // NOI18N
        spriteButton3.setBorder(null);
        spriteButton3.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                spriteButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(spriteButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 330, 30, 30));

        spriteButton4.setIcon(new javax.swing.ImageIcon("C:\\Users\\megan\\OneDrive\\Documents\\NetBeansProjects\\PAT2023\\resources\\picture.jpg")); // NOI18N
        spriteButton4.setBorder(null);
        spriteButton4.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                spriteButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(spriteButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 140, 20, 30));

        spriteButton5.setIcon(new javax.swing.ImageIcon("C:\\Users\\megan\\OneDrive\\Documents\\NetBeansProjects\\PAT2023\\resources\\picture.jpg")); // NOI18N
        spriteButton5.setBorder(null);
        spriteButton5.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                spriteButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(spriteButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(1110, 140, 10, 20));

        spriteButton6.setIcon(new javax.swing.ImageIcon("C:\\Users\\megan\\OneDrive\\Documents\\NetBeansProjects\\PAT2023\\resources\\picture.jpg")); // NOI18N
        spriteButton6.setBorder(null);
        spriteButton6.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                spriteButton6ActionPerformed(evt);
            }
        });
        getContentPane().add(spriteButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 110, 10, 20));

        infoButton.setBackground(new java.awt.Color(15, 28, 33));
        infoButton.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        infoButton.setForeground(new java.awt.Color(139, 118, 82));
        infoButton.setIcon(new javax.swing.ImageIcon("C:\\Users\\megan\\OneDrive\\Documents\\NetBeansProjects\\PAT2023\\resources\\infoIcon.png")); // NOI18N
        infoButton.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(139, 118, 82), 5, true));
        infoButton.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                infoButtonActionPerformed(evt);
            }
        });
        getContentPane().add(infoButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(1260, 110, 70, 60));

        backButton.setBackground(new java.awt.Color(15, 28, 33));
        backButton.setFont(new java.awt.Font("High Tower Text", 1, 24)); // NOI18N
        backButton.setForeground(new java.awt.Color(139, 118, 82));
        backButton.setText("<<");
        backButton.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(139, 118, 82), 5, true));
        backButton.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                backButtonActionPerformed(evt);
            }
        });
        getContentPane().add(backButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 90, 50));

        homeButton.setBackground(new java.awt.Color(15, 28, 33));
        homeButton.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        homeButton.setForeground(new java.awt.Color(139, 118, 82));
        homeButton.setText("HOME");
        homeButton.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(139, 118, 82), 5, true));
        homeButton.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                homeButtonActionPerformed(evt);
            }
        });
        getContentPane().add(homeButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(1220, 30, 110, 70));

        diaryButton.setBackground(new java.awt.Color(15, 28, 33));
        diaryButton.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        diaryButton.setForeground(new java.awt.Color(139, 118, 82));
        diaryButton.setIcon(new javax.swing.ImageIcon("C:\\Users\\megan\\OneDrive\\Documents\\NetBeansProjects\\PAT2023\\resources\\diaryIcon.jpg")); // NOI18N
        diaryButton.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(139, 118, 82), 5, true));
        diaryButton.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                diaryButtonActionPerformed(evt);
            }
        });
        getContentPane().add(diaryButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(1130, 30, 70, 70));

        spritesFoundLabel.setBackground(new java.awt.Color(15, 28, 33));
        spritesFoundLabel.setFont(new java.awt.Font("Perpetua Titling MT", 1, 36)); // NOI18N
        spritesFoundLabel.setForeground(new java.awt.Color(139, 118, 82));
        spritesFoundLabel.setText("jLabel1");
        spritesFoundLabel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(139, 118, 82), 5, true));
        spritesFoundLabel.setOpaque(true);
        getContentPane().add(spritesFoundLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 30, 70, 70));

        background.setIcon(new javax.swing.ImageIcon("C:\\Users\\megan\\OneDrive\\Documents\\NetBeansProjects\\PAT2023\\resources\\sleepingCompartmentBackground.png")); // NOI18N
        getContentPane().add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -330, 1400, 1200));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void infoButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_infoButtonActionPerformed
    {//GEN-HEADEREND:event_infoButtonActionPerformed
        this.dispose();
        new ObjectiveScreen().setVisible(true);
    }//GEN-LAST:event_infoButtonActionPerformed

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_backButtonActionPerformed
    {//GEN-HEADEREND:event_backButtonActionPerformed
        this.dispose();
        new DiningRoom().setVisible(true);
    }//GEN-LAST:event_backButtonActionPerformed

    private void homeButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_homeButtonActionPerformed
    {//GEN-HEADEREND:event_homeButtonActionPerformed
        this.dispose();
        new UserScreen().setVisible(true);
    }//GEN-LAST:event_homeButtonActionPerformed

    private void diaryButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_diaryButtonActionPerformed
    {//GEN-HEADEREND:event_diaryButtonActionPerformed
        try
        {
            new DiaryScreen().setVisible(true);
        } catch (SQLException ex)
        {
            Logger.getLogger(FindingGameScreen.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_diaryButtonActionPerformed

    private void spriteButton2ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_spriteButton2ActionPerformed
    {//GEN-HEADEREND:event_spriteButton2ActionPerformed
        try
        {
            //adding the fragment to the found fragments
            game.fragmentFound();
            spritesFoundLabel.setText(game.getNumFragmentsFound() + "/6");
            
            
            //disabling the button so it cannot be used anymore
            spriteButton2.setEnabled(false);
            spriteButton2.setOpaque(false);
            spriteButton2.setContentAreaFilled(false);
            spriteButton2.setFocusPainted(false);
            spriteButton2.setIcon(null);
            
        } catch (SQLException ex)
        {
            Logger.getLogger(FindingGameScreen.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex)
        {
            Logger.getLogger(FindingGameScreen.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_spriteButton2ActionPerformed

    private void spriteButton4ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_spriteButton4ActionPerformed
    {//GEN-HEADEREND:event_spriteButton4ActionPerformed
        try
        {
            //adding the fragment to the found fragments
            game.fragmentFound();
            spritesFoundLabel.setText(game.getNumFragmentsFound() + "/6");
            
            
            //disabling the button so it cannot be used anymore
            spriteButton4.setEnabled(false);
            spriteButton4.setOpaque(false);
            spriteButton4.setContentAreaFilled(false);
            spriteButton4.setFocusPainted(false);
            spriteButton4.setIcon(null);
            
        } catch (SQLException ex)
        {
            Logger.getLogger(FindingGameScreen.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex)
        {
            Logger.getLogger(FindingGameScreen.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_spriteButton4ActionPerformed

    private void spriteButton1ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_spriteButton1ActionPerformed
    {//GEN-HEADEREND:event_spriteButton1ActionPerformed
        try
        {
            //adding the fragment to the found fragments
            game.fragmentFound();
            spritesFoundLabel.setText(game.getNumFragmentsFound() + "/6");
            
            
            //disabling the button so it cannot be used anymore
            spriteButton1.setEnabled(false);
            spriteButton1.setOpaque(false);
            spriteButton1.setContentAreaFilled(false);
            spriteButton1.setFocusPainted(false);
            spriteButton1.setIcon(null);
            
        } catch (SQLException ex)
        {
            Logger.getLogger(FindingGameScreen.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex)
        {
            Logger.getLogger(FindingGameScreen.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_spriteButton1ActionPerformed

    private void spriteButton3ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_spriteButton3ActionPerformed
    {//GEN-HEADEREND:event_spriteButton3ActionPerformed
        try
        {
            //adding the fragment to the found fragments
            game.fragmentFound();
            spritesFoundLabel.setText(game.getNumFragmentsFound() + "/6");
            
            
            //disabling the button so it cannot be used anymore
            spriteButton3.setEnabled(false);
            spriteButton3.setOpaque(false);
            spriteButton3.setContentAreaFilled(false);
            spriteButton3.setFocusPainted(false);
            spriteButton3.setIcon(null);
            
        } catch (SQLException ex)
        {
            Logger.getLogger(FindingGameScreen.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex)
        {
            Logger.getLogger(FindingGameScreen.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_spriteButton3ActionPerformed

    private void spriteButton5ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_spriteButton5ActionPerformed
    {//GEN-HEADEREND:event_spriteButton5ActionPerformed
        try
        {
            //adding the fragment to the found fragments
            game.fragmentFound();
            spritesFoundLabel.setText(game.getNumFragmentsFound() + "/6");
            
            
            //disabling the button so it cannot be used anymore
            spriteButton5.setEnabled(false);
            spriteButton5.setOpaque(false);
            spriteButton5.setContentAreaFilled(false);
            spriteButton5.setFocusPainted(false);
            spriteButton5.setIcon(null);
            
        } catch (SQLException ex)
        {
            Logger.getLogger(FindingGameScreen.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex)
        {
            Logger.getLogger(FindingGameScreen.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_spriteButton5ActionPerformed

    private void spriteButton6ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_spriteButton6ActionPerformed
    {//GEN-HEADEREND:event_spriteButton6ActionPerformed
        try
        {
            //adding the fragment to the found fragments
            game.fragmentFound();
            spritesFoundLabel.setText(game.getNumFragmentsFound() + "/6");
            
            
            //disabling the button so it cannot be used anymore
            spriteButton6.setEnabled(false);
            spriteButton6.setOpaque(false);
            spriteButton6.setContentAreaFilled(false);
            spriteButton6.setFocusPainted(false);
            spriteButton6.setIcon(null);
            
        } catch (SQLException ex)
        {
            Logger.getLogger(FindingGameScreen.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex)
        {
            Logger.getLogger(FindingGameScreen.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_spriteButton6ActionPerformed



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backButton;
    private javax.swing.JLabel background;
    private javax.swing.JButton diaryButton;
    private javax.swing.JButton homeButton;
    private javax.swing.JButton infoButton;
    private javax.swing.JButton spriteButton1;
    private javax.swing.JButton spriteButton2;
    private javax.swing.JButton spriteButton3;
    private javax.swing.JButton spriteButton4;
    private javax.swing.JButton spriteButton5;
    private javax.swing.JButton spriteButton6;
    private javax.swing.JLabel spritesFoundLabel;
    // End of variables declaration//GEN-END:variables
}
