/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

import Backend.SceneMethods;
import java.io.IOException;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author megan
 */
public class SceneScreen extends javax.swing.JFrame
{
    SceneMethods sm = new SceneMethods();
    /**
     * Creates new form SceneScreen
     */
    public SceneScreen() throws SQLException, IOException
    {
        initComponents();
        //setting full screen
        this.setExtendedState(this.MAXIMIZED_BOTH);
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        characterPics = new javax.swing.JLabel();
        homeButton = new javax.swing.JButton();
        diaryButton = new javax.swing.JButton();
        infoButton = new javax.swing.JButton();
        backButton = new javax.swing.JButton();
        startButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        infoTextArea = new javax.swing.JTextArea();
        answerButton1 = new javax.swing.JButton();
        answerButton2 = new javax.swing.JButton();
        answerButton3 = new javax.swing.JButton();
        answerButton4 = new javax.swing.JButton();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        characterPics.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(139, 118, 82), 5, true));
        getContentPane().add(characterPics, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 50, 230, 250));

        homeButton.setBackground(new java.awt.Color(15, 28, 33));
        homeButton.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        homeButton.setForeground(new java.awt.Color(139, 118, 82));
        homeButton.setText("HOME");
        homeButton.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(139, 118, 82), 5, true));
        homeButton.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                homeButtonActionPerformed(evt);
            }
        });
        getContentPane().add(homeButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(1240, 30, 90, 70));

        diaryButton.setBackground(new java.awt.Color(15, 28, 33));
        diaryButton.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        diaryButton.setForeground(new java.awt.Color(139, 118, 82));
        diaryButton.setIcon(new javax.swing.ImageIcon("C:\\Users\\megan\\OneDrive\\Documents\\NetBeansProjects\\PAT2023\\resources\\diaryIcon.jpg")); // NOI18N
        diaryButton.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(139, 118, 82), 5, true));
        diaryButton.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                diaryButtonActionPerformed(evt);
            }
        });
        getContentPane().add(diaryButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(1150, 30, -1, 70));

        infoButton.setBackground(new java.awt.Color(15, 28, 33));
        infoButton.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        infoButton.setForeground(new java.awt.Color(139, 118, 82));
        infoButton.setIcon(new javax.swing.ImageIcon("C:\\Users\\megan\\OneDrive\\Documents\\NetBeansProjects\\PAT2023\\resources\\infoIcon.png")); // NOI18N
        infoButton.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(139, 118, 82), 5, true));
        infoButton.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                infoButtonActionPerformed(evt);
            }
        });
        getContentPane().add(infoButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(1250, 110, -1, 60));

        backButton.setBackground(new java.awt.Color(15, 28, 33));
        backButton.setFont(new java.awt.Font("High Tower Text", 1, 24)); // NOI18N
        backButton.setForeground(new java.awt.Color(139, 118, 82));
        backButton.setText("<<");
        backButton.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(139, 118, 82), 5, true));
        backButton.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                backButtonActionPerformed(evt);
            }
        });
        getContentPane().add(backButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, 80, 50));

        startButton.setBackground(new java.awt.Color(15, 28, 33));
        startButton.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        startButton.setForeground(new java.awt.Color(139, 118, 82));
        startButton.setText("START");
        startButton.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(139, 118, 82), 5, true));
        startButton.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                startButtonActionPerformed(evt);
            }
        });
        getContentPane().add(startButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 340, 80, 60));

        infoTextArea.setEditable(false);
        infoTextArea.setBackground(new java.awt.Color(15, 28, 33));
        infoTextArea.setColumns(20);
        infoTextArea.setFont(new java.awt.Font("Perpetua Titling MT", 1, 18)); // NOI18N
        infoTextArea.setForeground(new java.awt.Color(139, 118, 82));
        infoTextArea.setLineWrap(true);
        infoTextArea.setRows(5);
        infoTextArea.setWrapStyleWord(true);
        infoTextArea.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(139, 118, 82), 5, true));
        jScrollPane1.setViewportView(infoTextArea);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 150, 850, 440));

        answerButton1.setBackground(new java.awt.Color(15, 28, 33));
        answerButton1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        answerButton1.setForeground(new java.awt.Color(139, 118, 82));
        answerButton1.setText("A");
        answerButton1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(139, 118, 82), 5, true));
        answerButton1.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                answerButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(answerButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1130, 460, 80, 60));

        answerButton2.setBackground(new java.awt.Color(15, 28, 33));
        answerButton2.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        answerButton2.setForeground(new java.awt.Color(139, 118, 82));
        answerButton2.setText("B");
        answerButton2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(139, 118, 82), 5, true));
        answerButton2.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                answerButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(answerButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1220, 460, 80, 60));

        answerButton3.setBackground(new java.awt.Color(15, 28, 33));
        answerButton3.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        answerButton3.setForeground(new java.awt.Color(139, 118, 82));
        answerButton3.setText("C");
        answerButton3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(139, 118, 82), 5, true));
        answerButton3.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                answerButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(answerButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1130, 530, 80, 60));

        answerButton4.setBackground(new java.awt.Color(15, 28, 33));
        answerButton4.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        answerButton4.setForeground(new java.awt.Color(139, 118, 82));
        answerButton4.setText("D");
        answerButton4.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(139, 118, 82), 5, true));
        answerButton4.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                answerButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(answerButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1220, 530, 80, 60));

        background.setIcon(new javax.swing.ImageIcon("C:\\Users\\megan\\OneDrive\\Documents\\NetBeansProjects\\PAT2023\\resources\\redBackground.png")); // NOI18N
        getContentPane().add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -330, 1400, 1200));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void homeButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_homeButtonActionPerformed
    {//GEN-HEADEREND:event_homeButtonActionPerformed
        this.dispose();
        new UserScreen().setVisible(true);
    }//GEN-LAST:event_homeButtonActionPerformed

    private void diaryButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_diaryButtonActionPerformed
    {//GEN-HEADEREND:event_diaryButtonActionPerformed
        try
        {
            new DiaryScreen().setVisible(true);
        } catch (SQLException ex)
        {
            Logger.getLogger(SceneScreen.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_diaryButtonActionPerformed

    private void infoButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_infoButtonActionPerformed
    {//GEN-HEADEREND:event_infoButtonActionPerformed
        try
        {
            new ObjectiveScreen().setVisible(true);
        } catch (SQLException ex)
        {
            Logger.getLogger(SceneScreen.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_infoButtonActionPerformed

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_backButtonActionPerformed
    {//GEN-HEADEREND:event_backButtonActionPerformed
        this.dispose();
        new UserScreen().setVisible(true);
    }//GEN-LAST:event_backButtonActionPerformed

    private void answerButton1ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_answerButton1ActionPerformed
    {//GEN-HEADEREND:event_answerButton1ActionPerformed
        
    }//GEN-LAST:event_answerButton1ActionPerformed

    private void answerButton2ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_answerButton2ActionPerformed
    {//GEN-HEADEREND:event_answerButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_answerButton2ActionPerformed

    private void answerButton3ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_answerButton3ActionPerformed
    {//GEN-HEADEREND:event_answerButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_answerButton3ActionPerformed

    private void answerButton4ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_answerButton4ActionPerformed
    {//GEN-HEADEREND:event_answerButton4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_answerButton4ActionPerformed

    private void startButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_startButtonActionPerformed
    {//GEN-HEADEREND:event_startButtonActionPerformed
        startButton.remove(this);
        
        if(sm.isFirstScene())
        {
            try
            {
                sm.playFirstScene(characterPics, infoTextArea, answerButton1, answerButton2, answerButton3, answerButton4);
            } catch (SQLException ex)
            {
                Logger.getLogger(SceneScreen.class.getName()).log(Level.SEVERE, null, ex);
            } catch (IOException ex)
            {
                Logger.getLogger(SceneScreen.class.getName()).log(Level.SEVERE, null, ex);
            } catch (InterruptedException ex)
            {
                Logger.getLogger(SceneScreen.class.getName()).log(Level.SEVERE, null, ex);
            }
            if(!sm.isFirstScene())
            {
                new DiningRoom().setVisible(true);
                this.dispose();
            }
        }
    }//GEN-LAST:event_startButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton answerButton1;
    private javax.swing.JButton answerButton2;
    private javax.swing.JButton answerButton3;
    private javax.swing.JButton answerButton4;
    private javax.swing.JButton backButton;
    private javax.swing.JLabel background;
    private javax.swing.JLabel characterPics;
    private javax.swing.JButton diaryButton;
    private javax.swing.JButton homeButton;
    private javax.swing.JButton infoButton;
    private javax.swing.JTextArea infoTextArea;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton startButton;
    // End of variables declaration//GEN-END:variables
}
