/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

/**
 *
 * @author megan
 */
public class UserScreen extends javax.swing.JFrame
{

    /**
     * Creates new form UserScreen
     */
    public UserScreen()
    {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        title = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        userList = new javax.swing.JList<>();
        exitButton = new javax.swing.JButton();
        loadUserButton = new javax.swing.JButton();
        newUserButton = new javax.swing.JButton();
        deleteUserButton = new javax.swing.JButton();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        title.setIcon(new javax.swing.ImageIcon("C:\\Users\\megan\\OneDrive\\Documents\\NetBeansProjects\\PAT2023\\resources\\title.png")); // NOI18N
        getContentPane().add(title, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 60, 560, -1));

        userList.setBackground(new java.awt.Color(15, 28, 33));
        userList.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(139, 118, 82), 5, true));
        userList.setFont(new java.awt.Font("Perpetua Titling MT", 1, 18)); // NOI18N
        userList.setForeground(new java.awt.Color(139, 118, 82));
        userList.setModel(new javax.swing.AbstractListModel<String>()
        {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        userList.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_INTERVAL_SELECTION);
        userList.setAlignmentX(10.0F);
        userList.setAlignmentY(10.0F);
        jScrollPane1.setViewportView(userList);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 190, 450, 430));

        exitButton.setBackground(new java.awt.Color(15, 28, 33));
        exitButton.setFont(new java.awt.Font("Perpetua Titling MT", 1, 18)); // NOI18N
        exitButton.setForeground(new java.awt.Color(139, 118, 82));
        exitButton.setText("EXIT");
        exitButton.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(139, 118, 82), 5, true));
        getContentPane().add(exitButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 550, 250, 70));

        loadUserButton.setBackground(new java.awt.Color(15, 28, 33));
        loadUserButton.setFont(new java.awt.Font("Perpetua Titling MT", 1, 18)); // NOI18N
        loadUserButton.setForeground(new java.awt.Color(139, 118, 82));
        loadUserButton.setText("LOAD USER");
        loadUserButton.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(139, 118, 82), 5, true));
        getContentPane().add(loadUserButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 380, 250, 70));

        newUserButton.setBackground(new java.awt.Color(15, 28, 33));
        newUserButton.setFont(new java.awt.Font("Perpetua Titling MT", 1, 18)); // NOI18N
        newUserButton.setForeground(new java.awt.Color(139, 118, 82));
        newUserButton.setText("NEW USER");
        newUserButton.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(139, 118, 82), 5, true));
        newUserButton.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                newUserButtonActionPerformed(evt);
            }
        });
        getContentPane().add(newUserButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 200, 250, 70));

        deleteUserButton.setBackground(new java.awt.Color(15, 28, 33));
        deleteUserButton.setFont(new java.awt.Font("Perpetua Titling MT", 1, 18)); // NOI18N
        deleteUserButton.setForeground(new java.awt.Color(139, 118, 82));
        deleteUserButton.setText("DELETE USER ");
        deleteUserButton.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(139, 118, 82), 5, true));
        getContentPane().add(deleteUserButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 290, 250, 70));

        background.setIcon(new javax.swing.ImageIcon("C:\\Users\\megan\\OneDrive\\Documents\\NetBeansProjects\\PAT2023\\resources\\A-1920s-style-sleeper-train-with-an-image-size-of-1920x1080.png")); // NOI18N
        getContentPane().add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(-70, -30, 1920, 1020));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void newUserButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_newUserButtonActionPerformed
    {//GEN-HEADEREND:event_newUserButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_newUserButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(UserScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(UserScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(UserScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(UserScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                new UserScreen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel background;
    private javax.swing.JButton deleteUserButton;
    private javax.swing.JButton exitButton;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton loadUserButton;
    private javax.swing.JButton newUserButton;
    private javax.swing.JLabel title;
    private javax.swing.JList<String> userList;
    // End of variables declaration//GEN-END:variables
}
